apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecsdemo-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: eksdemo-frontend
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/aws-containers/ecsdemo-frontend.git
    targetRevision: main
    path: kubernetes/helm/ecsdemo-frontend
    helm:
      parameters:
      - name: ingress.enabled
        value: true    
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
