apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecsdemo-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ecsdemo-frontend
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.apps.ecsdemoFrontend.repoURL }}
    targetRevision: {{ .Values.spec.apps.ecsdemoFrontend.targetRevision }}
    path: {{ .Values.spec.apps.ecsdemoFrontend.path }}
    helm:
      parameters:
      - name: ingress.enabled
        value: "true"
      - name: ingress.className
        value: "alb"
      - name: ingress.annotations."alb.ingress.kubernetes.io/group.name"
        value: "ecsdemo"        
      #- name: ingress.annotations."alb.ingress.kubernetes.io/target-type"
      #  value: "ip"
      - name: replicaCount
        value: "3"
      - name: image.repository
        value: "public.ecr.aws/seb-demo/ecsdemo-frontend"
      - name: resources.requests.cpu
        value: "200m"
      - name: resources.limits.cpu
        value: "400m"        
      - name: resources.requests.memory
        value: "256Mi"
      - name: resources.limits.memory
        value: "512Mi"        


  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=false # https://github.com/argoproj/argo-cd/issues/7799
