apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecsdemo-frontend
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
    - namespace: ecsdemo-frontend
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/aws-containers/ecsdemo-frontend.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecsdemo-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ecsdemo-frontend
  destination:
    namespace: ecsdemo-frontend
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.apps.ecsdemoFrontend.repoURL }}
    targetRevision: {{ .Values.spec.apps.ecsdemoFrontend.targetRevision }}
    path: {{ .Values.spec.apps.ecsdemoFrontend.path }}
    helm:
      values: |-
      {{ toYaml .Values.spec.apps.ecsdemoFrontend | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=false # https://github.com/argoproj/argo-cd/issues/7799
