apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecsdemo-crystal
  namespace: argocd
spec:
  destinations:
    - namespace: ecsdemo-crystal
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/aws-containers/ecsdemo-crystal.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecsdemo-crystal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ecsdemo-crystal
  destination:
    namespace: ecsdemo-crystal
    server: {{.Values.spec.destination.server}}
  source:
    repoURL: {{.Values.spec.apps.ecsdemoCrystal.repoURL}}
    targetRevision: {{.Values.spec.apps.ecsdemoCrystal.targetRevision}}
    path: {{.Values.spec.apps.ecsdemoCrystal.path}}
    helm:
      parameters:
        - name: replicaCount
          value: '3'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=false # https://github.com/argoproj/argo-cd/issues/7799
