apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecsdemo-nodejs
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
    - namespace: ecsdemo-nodejs
      server: https://kubernetes.default.svc
  sourceRepos:
    - git@github.com:aws-containers/ecsdemo-nodejs.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecsdemo-nodejs
  namespace: argocd
  labels:
    {{- toYaml .Values.labels | nindent 4 }}  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ecsdemo-nodejs
  destination:
    namespace: ecsdemo-nodejs
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.apps.ecsdemoNodejs.repoURL }}
    targetRevision: {{ .Values.spec.apps.ecsdemoNodejs.targetRevision }}
    path: {{ .Values.spec.apps.ecsdemoNodejs.path }}
    helm:
      parameters:
        - name: replicaCount
          value: '3'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=false # https://github.com/argoproj/argo-cd/issues/7799
