apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-carmen
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: team-carmen
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://github.com/CarmenAPuccio/GeoLocationAPI
    path: templates
    targetRevision: HEAD
    helm:
      parameters:
      - name: spec.ingress.host
        value: {{ .Values.spec.ingress.host }}
      - name: spec.ingress.type
        value: {{ .Values.spec.ingress.type }}        
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true