apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: burnham-ingress
  namespace: team-burnham
  labels:
    app: burnham-ingress-{{ .Values.spec.env }}
  annotations:
{{ if eq .Values.spec.ingress.type "nginx" }} 
    #nginx annotations  
{{ else }}    
    {{ if .Values.spec.ingress.host }} # we can't use grouping without custom domain    
    alb.ingress.kubernetes.io/group.name: burnham
    {{ end }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: 'ip'
  {{ if .Values.spec.ingress.host }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  {{ else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  {{ end }}     
    alb.ingress.kubernetes.io/backend-protocol: 'HTTP'
{{ end }}  
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=Burnham
spec:
{{ if eq .Values.spec.ingress.type "nginx" }}  
  kubernetes.io/ingress.class: "nginx"
{{ else }}
  ingressClassName: alb
{{ end }}
  rules:
{{ if .Values.spec.ingress.host }}  
  - host: burnham.{{ .Values.spec.ingress.host }}  
{{ else }}  
  - host: 
{{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eks-example
            port: 
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eks-example
  labels:
    app: burnham-ingress-{{ .Values.spec.env }}  
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: eks-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-example
  labels:
    app: burnham-deployment-{{ .Values.spec.env }}
spec:
  #replicas: {{ int .Values.spec.replicas }}
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: eks-example
  template:
    metadata:
      labels:
        app: eks-example
        seb: test
    spec:
      containers:
        - name: eks-example
          image: public.ecr.aws/seb-demo/eks-example:6d1d832508017919344c62c5eaece159fccffa79
          imagePullPolicy: Always
          env:
          - name: CLUSTER_NAME
            value: {{ .Values.spec.clusterName }}
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 50Mi            
      # nodeSelector:
      #   team: burnham
      #   type: karpenter
      # tolerations:
      #   - key: 'burnham'
      #     operator: 'Exists'
      #     effect: 'NoSchedule'
